# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c764912394f3bd67633709be6ae47de4cccc1fe16276c5167f8301c3c95f4768216f2e8cb916c52acb35639e9ff5fe1d3afb14ff6bdfae514fb81068b7b1e8e

test:
  secret_key_base: 5b03e3a4dbba47f3d221f0a722b1bdb86a6b5d313cc431d20955c65fd6f846169b54d55a4a1358b6206f733d1a528686d7f842b5ac43c14d94cd1ce403971eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
